#!/usr/bin/env php
<?php

ini_set('display_errors', 1);
error_reporting(E_ALL);

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('FilcPress Installer', '0.1');
$app->add(new FilcPress\Installer\Console\NewCommand);

$app->run();
